import type { Metadata } from "next";
import { DM_Sans, DM_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";
import { ViewTransitions } from "next-view-transitions";
import QueryClientProviderApp from "@/providers/query-client-provider";

const DMSans = DM_Sans({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const DMMono = DM_Mono({
	weight: "400",
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Nest hackthon",
	description: "Generated by create next app",
};

export default async function LocaleLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html>
				<body className={`${DMSans.variable} ${DMMono.variable} antialiased`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<QueryClientProviderApp>{children}</QueryClientProviderApp>
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</ViewTransitions>
	);
}
